# Generated by Django 4.1.5 on 2023-03-20 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scenario_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioSolution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('solution_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('solution_type', models.CharField(choices=[('supervised', 'Supervised'), ('unsupervised', 'Unsupervised')], max_length=20)),
                ('training_file', models.FileField(blank=True, null=True, upload_to='files')),
                ('test_file', models.FileField(blank=True, null=True, upload_to='files')),
                ('protected_features', models.CharField(blank=True, max_length=200, null=True)),
                ('protected_values', models.CharField(blank=True, max_length=200, null=True)),
                ('target_column', models.CharField(default='target', max_length=200, null=True)),
                ('outlier_data_file', models.FileField(blank=True, null=True, upload_to='files')),
                ('favourable_outcome', models.CharField(blank=True, default='1', max_length=200)),
                ('factsheet_file', models.FileField(blank=True, null=True, upload_to='files')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='files')),
                ('metrics_mappings_file', models.FileField(blank=True, null=True, upload_to='files')),
                ('weights_metrics', models.FileField(blank=True, null=True, upload_to='files')),
                ('weights_pillars', models.FileField(blank=True, null=True, upload_to='files')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
